name: PR Checks
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3'

      - name: Install dependencies
        run: bun ci

      - name: Build
        run: bun build:binary

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3'

      - name: Install dependencies
        run: bun ci

      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3'

      - name: Install dependencies
        run: bun ci

      - name: Run Unit tests
        run: bun test